version: 2.1

jobs:
  lint_helm_charts:
    working_directory: ~/CommonHelmCharts
    docker:
      - image: quay.io/helmpack/chart-testing:v3.0.0-rc.1
    steps:
      - checkout
      - run:
          name: Lint Python Django Common Helm Charts
          working_directory: ~/CommonHelmCharts/python_django_monolith_apps
          command: |
              ct lint --charts common

  package_upload_common_helm_chart:
    working_directory: ~/CommonHelmCharts
    docker:
      - image: quay.io/helmpack/chart-releaser:v1.0.0-beta.1
    steps:
      - checkout
      - run:
          name: Package Common Chart
          working_directory: ~/CommonHelmCharts/python_django_monolith_apps/common
          command: |
              ls

workflows:
  version: 2
  commonhelmcharts:
    jobs:
    - lint_helm_charts
    - package_upload_common_helm_chart
