{{- define "common.certificate" -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ required "The name for the certificate should be provided." .Values.certificate.name }}"
spec:
  secretName: {{ .Values.certificate.name }}-ssl-cert
  dnsNames:
  {{- range .Values.hosts }}
    - {{ .url }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.issuerRefName }}
{{- end }}
