{{- define "common.clusterissuer" -}}
{{- range .Values.clusterissuers }}
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: "{{ .name }}"
spec:
  acme:
    server: "{{ .server }}"
    email: "{{ .email }}"
    privateKeySecretRef:
      name: "{{ .name }}-private-key"
    solvers:
{{ toYaml .solvers | trim | indent 4 }}

---
{{- end }}
{{- end -}}
