apiVersion: v2
name: common
description: "This bug fix fixes an error on the deployment container's spec. It changes the resources definition key from 'limit' to 'limits'"
type: library
version: 0.3.1
home: https://github.com/JamesKirkAndSpock/CommonHelmCharts/
appVersion: 0.3.1
maintainers:
    - name: JamesKirkAndSpock
