apiVersion: v2
name: common
description: "Fix typo on API version"
type: library
version: 0.5.2
home: https://github.com/JamesKirkAndSpock/CommonHelmCharts/
appVersion: 0.5.2
maintainers:
    - name: JamesKirkAndSpock
