apiVersion: v2
name: common
description: "Add a Certificate Object"
type: library
version: 0.5.1
home: https://github.com/JamesKirkAndSpock/CommonHelmCharts/
appVersion: 0.5.1
maintainers:
    - name: JamesKirkAndSpock
